name: deploy

on:
  push:
    branches: [ new-website ]

jobs:
  release:
    name: Deploy product to OBS and refresh CDN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment 
      uses: actions/setup-node@v1
      with:
        node-version: 12 

    - name: Build
      run: |
        npm install
        CI=false npm run build
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main-artifact
        path: |
          build
    - name: Deploy-ExcludeTXT
      uses: summer-ospp/infra-ci-s3-sync@master
      with:
        args: --acl public-read --follow-symlinks --exclude '*.txt'
      env:
        AWS_S3_BUCKET: summer-test-homepage
        AWS_ACCESS_KEY_ID: ${{ secrets.HOMEPAGE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HOMEPAGE_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.HOMEPAGE_ENDPOINT }}
        SOURCE_DIR: 'build'

    - name: Deploy-IncludeTXT
      uses: summer-ospp/infra-ci-s3-sync@master
      with:
        args: --acl public-read --follow-symlinks --exclude '*' --include '*.txt' --content-type 'text/plain;charset=UTF-8'
      env:
        AWS_S3_BUCKET: summer-test-homepage
        AWS_ACCESS_KEY_ID: ${{ secrets.HOMEPAGE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HOMEPAGE_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.HOMEPAGE_ENDPOINT }}
        SOURCE_DIR: 'build'
